server:
  host: "localhost"
  port: ":8081"

mysql:
  host: "localhost"
  port: "3306"
  user: "user"
  password: "password"
  dbname: "BuddyLink"

minio:
  endpoint: "http://127.0.0.1:9000"
  access_key_id: "admin"
  secret_access_key: "admin"
  use_ssl: false

smtp:
  email: "test@xxx.com"
  password: "root"
  host: "smtp.xxx.com"
  port: "25"
  ssl: true

redis:
  host: "127.0.0.1"
  port: "27017"
  password: "password"
  db: 0

message:
  queue_db: "6"
  pool_db: "7"